services:
  # 1. La Gateway : Isole Alpaca-py
  gateway:
    build: ./gateway
    env_file: .env
    develop:
      watch:
      - action: sync+restart
        path: ./gateway
        target: /app
    restart: unless-stopped
    ports:
      - "8000:8000"
    networks:
      - trading-net

  # 2. Le Cerveau : Utilise la Gateway
  brain:
    build: ./bot
    env_file: .env
    depends_on:
      - gateway
      - ollama
    develop:
      watch:
      - action: sync+restart
        path: ./bot
        target: /brain

    environment:
      - OLLAMA_HOST=http://ollama:11434
    networks:
      - trading-net

  ollama:
    image: ollama/ollama:latest
    container_name: trading_ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama  # PERSISTANCE DES MODÈLES (Indispensable)
    environment:
      - OLLAMA_DEBUG=1
    networks:
      - trading-net
    # 👇 Active ceci si tu as une carte NVIDIA pour accélérer l'IA
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: always

  # 3. Observabilité
  
  dashboard:
    build: ./dashboard      # Construit l'image depuis ton dossier dashboard/
    container_name: trading_dashboard
    develop:
      watch:
      - action: sync+restart
        path: ./dashboard
        target: /app
    ports:
      - "8501:8501"         # Port par défaut de Streamlit
    volumes:
      - ./dashboard:/app    # IMPORTANT : Permet de modifier app.py sans redémarrer le conteneur (Hot-reload)
    environment:
      - GATEWAY_URL=http://gateway:8000
    depends_on:
      - gateway
    networks:
      - trading-net
      
  # grafana:
  #   image: grafana/grafana:latest
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./grafana/provisioning:/etc/grafana/provisioning
  #   networks:
  #     - trading-net

volumes:
  ollama_data:

networks:
  trading-net:
    driver: bridge