
services:
  # 1. La Gateway : Isole Alpaca-py
  gateway:
    build: ./gateway
    env_file: 
     - .env
    develop:
      watch:
      - action: sync+restart
        path: ./gateway
        target: /app
    restart: unless-stopped
    ports:
      - "8000:8000"
    networks:
      - trading-net

  # 2. Le Cerveau : Utilise la Gateway
  brain:
    build: ./bot
    env_file: .env
    restart: unless-stopped
    depends_on:
      - gateway
    develop:
      watch:
      - action: sync+restart
        path: ./bot
        target: /brain
    networks:
      - trading-net

  # 3. Observabilité
  
  dashboard:
    build: ./dashboard      # Construit l'image depuis ton dossier dashboard/
    container_name: trading_dashboard
    develop:
      watch:
      - action: sync+restart
        path: ./dashboard
        target: /app
    ports:
      - "8501:8501"         # Port par défaut de Streamlit
    volumes:
      - ./dashboard:/app   
    environment:
      - GATEWAY_URL=http://gateway:8000
    depends_on:
      - gateway
    networks:
      - trading-net
      
  # grafana:
  #   image: grafana/grafana:latest
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./grafana/provisioning:/etc/grafana/provisioning
  #   networks:
  #     - trading-net

networks:
  trading-net:
    driver: bridge