[pytest]
# Configuration de pytest

testpaths = pytest
python_files = test*.py
python_classes = Test*
python_functions = test_*

# Options
addopts = 
    -v
    --tb=short
    --strict-markers
    -ra

markers =
    unit: test unitaire
    integration: test d'intégration
    slow: test lent
    live: test avec données en direct

filterwarnings =
    ignore::DeprecationWarning
    ignore::PendingDeprecationWarning
